# Taken from: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - if: runner.os == 'Linux'
      name: Install packages
      run:  |
            sudo apt install libgl1-mesa-dev zip

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - if: runner.os == 'Linux'
      name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: ainby_linux
        path: ${{ steps.strings.outputs.build-output-dir }}/bin/*

    - if: runner.os == 'Windows'
      name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: ainby_win
        path: ${{ steps.strings.outputs.build-output-dir }}/bin/Release/*
